server:
  port: 8080
info:
  name: Application-master
  desc: 项目启动
spring:
  application:
    name: ${info.name}
eureka:
  client:
    enabled: true
    fetch-registry: true  #是否从eureka获取信息
    register-with-eureka: true #是否注册到eureka
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761

